### ISSUE TITLE
AlreadyConnectedException if Graylog is restarted but application keeps working

### ISSUE THREAD

**Issue by andrey-chernyshev** [mp911de/logstash-gelf#109] opened 2017-02-22 12:47 UTC
I'm using Gelf TCP logback appender to send the logs to Graylog 2.2.1+4829190 running in AWS ECS2 docker container. Restarting the Graylog container while keeping the reporting application running leads to the following exception:

```
15:23:57,701 |-ERROR in biz.paluch.logging.gelf.logback.GelfLogbackAppender[GRAYLOG] - Could not send GELF message: null java.nio.channels.AlreadyConnectedException
	at java.nio.channels.AlreadyConnectedException
```

I believe the problem could be in this part of GelfTCPSender code:

```
for (int i = 0; i < deliveryAttempts; i++) {
try {
                // (re)-connect if necessary
                if (!isConnected()) {
                    synchronized (ioLock) {
                        connect();
                    }
                }
      ...
} catch (IOException e) {
 Closer.close(channel());
```

The problem is that AlreadyConnectedException does not sublclass from IOException, hence the catch does not occur at this point and the the expected connection recovery never happens.
It would be very easy to break application logging with Graylog service restart because the reporting application never leaves the already connected state and is no longer able to report the logs.

How about catching more general Exception in this code block?

**Comment by mp911de** [comment] 2017-02-22 13:39
That's a duplicate of #107.

**Closed by mp911de** 2017-02-22 13:39 UTC
Labels: bug, duplicate
