### ISSUE TITLE
Tomcat deployment : potential memory leak

### ISSUE THREAD

**Issue by meveno** [mp911de/logstash-gelf#218] opened 2019-12-11 09:35 UTC
We're using GelfLogbackAppender withing our application and when undeploying a war in tomcat, we see warning from tomcat about a potential memory leak :

> 11-Dec-2019 09:51:31.840 SEVERE [Catalina-utility-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [integration-rejeu] created a ThreadLocal with key of type [biz.paluch.logging.gelf.intern.OutputAccessor$OutputAccessorPoolHolder$2] (value [biz.paluch.logging.gelf.intern.OutputAccessor$OutputAccessorPoolHolder$2@712b79d2]) and a value of type [biz.paluch.logging.gelf.intern.OutputAccessor.ByteBufferOutputStream] (value [biz.paluch.logging.gelf.intern.OutputAccessor$ByteBufferOutputStream@172899f1]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> 11-Dec-2019 09:51:31.840 SEVERE [Catalina-utility-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [integration-rejeu] created a ThreadLocal with key of type [biz.paluch.logging.gelf.GelfMessageAssembler$1] (value [biz.paluch.logging.gelf.GelfMessageAssembler$1@2eb7d464]) and a value of type [biz.paluch.logging.gelf.intern.PoolingGelfMessageBuilder] (value [biz.paluch.logging.gelf.intern.PoolingGelfMessageBuilder@61d33e41]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> 11-Dec-2019 09:51:31.841 SEVERE [Catalina-utility-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [integration-rejeu] created a ThreadLocal with key of type [biz.paluch.logging.gelf.intern.OutputAccessor$OutputAccessorPoolHolder$1] (value [biz.paluch.logging.gelf.intern.OutputAccessor$OutputAccessorPoolHolder$1@57762a06]) and a value of type [biz.paluch.logging.gelf.intern.OutputAccessor.ByteBufferOutputAccessor] (value [biz.paluch.logging.gelf.intern.OutputAccessor$ByteBufferOutputAccessor@3378d7d1]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> 11-Dec-2019 09:51:31.851 SEVERE [Catalina-utility-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [integration-rejeu] created a ThreadLocal with key of type [biz.paluch.logging.gelf.intern.PoolHolder$ThreadLocalPoolHolder$1] (value [biz.paluch.logging.gelf.intern.PoolHolder$ThreadLocalPoolHolder$1@5ba52236]) and a value of type [biz.paluch.logging.gelf.intern.ReusableGzipOutputStream] (value [biz.paluch.logging.gelf.intern.ReusableGzipOutputStream@3d65155e]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

May be some cleanup work is not correctly done ...

Our configuration file :
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>

    <springProfile name="prod">
        <appender name="gelf" class="biz.paluch.logging.gelf.logback.GelfLogbackAppender">
            <host>${GELF_URL}</host>
            <port>${GELF_UDP_PORT}</port>
            <version>1.1</version>
            <facility>gelf-logger</facility>
            <extractStackTrace>true</extractStackTrace>
            <filterStackTrace>true</filterStackTrace>
            <includeLocation>true</includeLocation>
            <mdcProfiling>true</mdcProfiling>
            <timestampPattern>yyyy-MM-dd HH:mm:ss,SSSZZZ</timestampPattern>
            <maximumMessageSize>8192</maximumMessageSize>
            <includeFullMdc>true</includeFullMdc>
            <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                <level>INFO</level>
            </filter>
        </appender>

        <root level="INFO">
            <appender-ref ref="gelf"/>
        </root>
    </springProfile>

    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
    </root>
</configuration>
`

**Environment :**

Maven dependencies : 

- biz.paluch.logging:logstash-gelf:1.13.0
- ch.qos.logback:logback-core:1.2.3
 
Using :

- Spring boot
- Deployed in war mode into tomcat
- docker image : tomcat:9-jdk8-slim

**Comment by mp911de** [comment] 2019-12-11 16:07
Thanks for the report. That's a duplicate of #159. Retention of `ThreadLocal` values becomes only a leak if you're using hot-redeploy. As per #159, there isn't really anything we can do here.

**Closed by mp911de** 2019-12-11 16:07 UTC
Labels: status: duplicate
