### ISSUE TITLE
Issue with chunked message when using logback

### ISSUE THREAD

**Issue by Thaoden** [mp911de/logstash-gelf#198] opened 2019-05-14 10:33 UTC
Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the logstash-gelf version and environment so it's obvious which version is affected: logstash-gelf-1.13.0 in conjunction with `logback`
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior. Not applicable, see below

Not sure if this is the right spot to ask, but I'll try anyway:

I'm currently facing a problem when trying to send large messages that need to be chunked, apparently only the first chunk of the message is sent, the remaining chunks are dropped.

When dumping the UDP traffic with tcpdump and analyzing the packages with Wireshark, a given package begins with
> 1e 0f b5 d9 0b 5e 6e 2e 64 65 00 02 ...

indicating a message consisting of two chunks. However the next messages all begin with 
> 1f 8b 08 00 00 00 00 00 00 00 ad 90 ...

so it seems the remainder of the chunked message is not sent over the wire.

Thanks for any hints!

**Comment by mp911de** [comment] 2019-05-16 09:15
Thanks for reporting. Can you provide us with a reproducer? We have [integration tests](https://github.com/mp911de/logstash-gelf/blob/2f26186b8a978882865d81272a277e0c8e0e8c49/src/test/java/biz/paluch/logging/gelf/log4j2/GelfLogAppenderNettyUdpIntegrationTests.java#L130) for sending chunked messages that currently verify chunked transport. It would be good to fix a potential issue if our test is missing something.

**Comment by Thaoden** [comment] 2019-05-16 12:37
Thanks for the reply!

My message load is 20.815 UTF8 chars in length, it contains encrypted data and thus can not be compressed efficiently. I can't share the complete message, I could try to redact parts of it if need be.

Sadly I cannot send a message directly to the logger as I have a third party software that handles the logging.

**Comment by mp911de** [comment] 2019-05-16 13:08
This is perfectly fine. We don't need the original message, just something that cannot be compressed efficiently and therefore requires a series of chunks.

**Comment by Thaoden** [comment] 2019-05-17 12:40
Sorry for the delay, I have attached the [log.txt](https://github.com/mp911de/logstash-gelf/files/3191490/log.txt). 

I have also attached the [dump.txt](https://github.com/mp911de/logstash-gelf/files/3191447/dump.txt) that I got by inspecting the tcp dump in Wireshark, exporting the payload to a .zip and unzipping. Notice that after replacing `\n` by a newline, the last few lines differ in the dump and in the "expected" load, but maybe I made an error while extracting the dump.

**Comment by mp911de** [comment] 2019-05-17 12:42
Thanks a lot.

**Comment by Thaoden** [comment] 2019-06-12 10:42
Are there any news on this?

**Comment by mp911de** [comment] 2019-06-12 18:58
I hadn't time yet to debug and trace down the issue.

**Comment by Thaoden** [comment] 2019-06-13 06:27
Anything I can do to help?

**Comment by mp911de** [comment] 2019-06-13 14:52
I tried to reproduce the issue via `GelfLogAppenderNettyUdpIntegrationTests` with no luck (using the data from the provided `dump.txt`. The message is sent properly when trying to reproduce the issue locally. 

How much traffic is there in your system? Could it be, that send buffers are full and therefore some bytes get dropped?

**Comment by Thaoden** [comment] 2019-06-13 16:39
The system sends a messahe over a TCP connection, that message triggers a log entry that in turn is sent over the wire, but it should not be too much to handle.

Note though that `dump.xml` is the file where parts of the payload were dropped and replaced; `log.txt` is the payload that is expected to get through.

**Comment by mp911de** [comment] 2019-06-13 17:05
Can you reliably reproduce the issue? If so, then I can set up a branch so we can experiment to find out what’s going on.

**Comment by Thaoden** [comment] 2019-06-14 07:21
I think so. I will try next week to collect additional dumps and will have a look if all those payloads are truncated.

**Comment by Thaoden** [comment] 2019-06-26 12:51
Sorry for the delay.

I collected some more dumps, three requests exceeded 8192 bytes and were truncated, or rather only the first chunk was sent.

**Comment by mp911de** [comment] 2019-06-26 14:27
Can you debug what happens in https://github.com/mp911de/logstash-gelf/blob/a7a8225ec063031da59596840341d166700bc591/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfUDPSender.java#L60-L67?

I'm not able to reproduce the issue.

**Comment by Thaoden** [comment] 2019-06-26 15:37
Sadly, I cannot debug it as I don't have a Java Dev environment; I merely use the logstash-gelf library in conjunction with a third party application.

I see there is a `reportError` method - where does it report errors to? Are there any metrics logged somewhere, like log server, max message size, buffer size, ...?

**Comment by sfuhrm** [comment] 2020-01-02 15:52
@Thaoden can you please re-verify? 
I cross-checked your finding today with Wireshark and the messages look ok to this spec: https://docs.graylog.org/en/3.1/pages/gelf.html

Here's an example of two logs that are as well **fragmented** as **chunked**:

[chunked.zip](https://github.com/mp911de/logstash-gelf/files/4016417/chunked.zip)

### UDP No 1
 Lengh `8204`
 Magic: `1e 0f`
 Message ID: `22 cb 08 c2 09 de b9 1c`
 Sequence Number: `00`
 Sequence Count: `03`

### UDP No 2
 Lengh `8204`
 Magic: `1e 0f`
 Message ID: `22 cb 08 c2 09 de b9 1c`
 Sequence Number: `01`
 Sequence Count: `03`
 
### UDP No 3
 Lengh `5571`
 Magic: `1e 0f`
 Message ID: `22 cb 08 c2 09 de b9 1c`
 Sequence Number: `02`
 Sequence Count: `03`
 
For me that looks like perfectly encoded sequences.

Please note that usually the UDP packets are fragmented and you should not look at a fragment alone, but at the re-assembled UDP packet in Wireshark.

**Comment by mp911de** [comment] 2020-01-08 16:01
Thanks a lot @sfuhrm. I'd like to close this ticket as we cannot proceed here without further details and we're not able to obtain further details.

**Closed by mp911de** 2020-01-08 16:01 UTC
Labels: status: waiting-for-triage

**Comment by Thaoden** [comment] 2020-01-12 18:52
@sfuhrm Thanks for the hint, I'll check in the next days.

@mp911de Thanks for trying to find the problem, I understand this is quite of a stale issue. If I ever find anything new, I'll chime in again!
