### ISSUE TITLE
Default value of maximumMessageSize is too large for default networks

### ISSUE THREAD

**Issue by waldeinburg** [mp911de/logstash-gelf#204] opened 2019-07-05 12:15 UTC
Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the logstash-gelf version and environment so it's obvious which version is affected: 1.13.0 with Log4j2 2.12.0
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.
1. Run `ip link` to check your network MTU. The following will assume MTU 1500.
2. Run `tcpdump -i any -vv udp port 12201` or wireshark or similar
3. With the standard `maximumMessageSize` (8192), produce a log message resulting in a GELF message larger than the network MTU minus 40 bytes. I.e., with MTU 1500 it should be 1460 bytes. A message of 20K chars should do.
4. Observe the output from tcpdump: The package should have a "bad length" notice unless the DF flag is not set (which I think is the Java default). The package have been dropped by the kernel. I have confirmed this by producing the log inside a virtual machine and running wireshark in the host: The package never leaves the VM.
5. Set `maximumMessageSize` to 1460 and repeat step 3-4. The packages should not be rejected this time.

This issue resembles #198, but that issue is that only the first chunk is transmitted when the message is chunked but the whole message is transmitted if `maximumMessageSize` is large enough. This kind of contradicts my issue, but here's my analysis anyway:

The problem is that the default value of `maximumMessageSize` is too large for a standard MTU (1500). It seems to be taken from the [GELF documentation](https://docs.graylog.org/en/3.0/pages/gelf.html). I don't know where that number comes from, but it will only work if jumbo frames are enabled on the network, which AFAIK is not wise to assume (cf. https://en.wikipedia.org/wiki/Maximum_transmission_unit#IP_MTUs_for_common_media).

*Suggested solution:* Change the default value of `maximumMessageSize` to 1460 (1500 minus 20 bytes IP header, 8 bytes UDP header and 12 bytes GELF header). And document that MTU minus 40 bytes is the maximum value that `maximumMessageSize` can be.

**Comment by mp911de** [comment] 2019-07-05 17:17
Thanks a lot for the thorough analysis. Until now ( ~ 6 years since inception), no one has brought up that issue yet. It makes sense to streamline the default for a standard MTU but we need to check how this affects our pooled buffers.

**Comment by sfuhrm** [comment] 2020-01-02 15:22
@waldeinburg Please note that UDP packets can be as big as 64k independent of your MTU. I don't see why the GELF documentation says they are usually only be 8192 ( https://docs.graylog.org/en/3.1/pages/gelf.html ).

When a UDP packet is larger than the network interfaces MTU (usually 1500), the IP stack needs to fragment the UDP packet (see https://en.wikipedia.org/wiki/IP_fragmentation). The remote IP stack will then reassemble the fragmented UDP packet and pass it to the application as a whole, totally transparent to the application.

GELF should rely on a working IP stack (fragmentation / defragmentation works).

The "bad length" message you're getting from tcpdump is actually a misconcept of tcpdump itself which I could reproduce. When UDP packets bigger than the MTU are fragmented, the fragmented IP packets are smaller than the logical UDP packet, thus the problem.

I could not reproduce your finding of a set "don't fragment" flag. AFAIK this flag requires you to have a raw IP socket.

For the sake of reproducability I've attached a Wireshark pcapng file (zipped) of two gelf UDPs being fragmented:

[doesfragment.zip](https://github.com/mp911de/logstash-gelf/files/4016317/doesfragment.zip)

Please let's not reduce the maximumMessageSize because it should work fine with every MTU. 

Let's understand more what problem you're facing. Can you go more into detail?

**Comment by waldeinburg** [comment] 2020-01-03 08:47
@sfuhrm I wonder what may cause the difference between our systems handling of the DF bit. I was having the impression that it was a Java default not to do fragmentation on UDP packets but I cannot remember how I reached that conclusion.

No matter what I think this issue boils down to two questions: Do we consider relying on UDP fragmentation a safe default or not? And if we are in doubt about about UDP fragmentation, do we consider the overhead of GELF chunking trivial or not?

It is my impression that is is generally recommended to [avoid UDP fragmentation](https://info.stack8.com/blog/udp-fragmentation-why-should-you-avoid-it).

If we consider UDP fragmentation safe, why bother doing application level fragmentation, which is just what GELF chunking is? If we are concerned with overhead of chunking we might then as well set an even larger maximumMessageSize.
Also note that even if the GELF documentation was right, the 8192 byte maximumMessageSize would be wrong because it does not leave room for the headers.

On the other hand, if we consider the overhead of GELF chunking trivial we might as well avoid the UDP fragmentation and [the problems it may cause in some environments](https://github.com/docker/for-win/issues/1144).

Even though the IP header contains fragment offset information it seems that one of the potential problems of UDP fragmentation is reordering. It seems that [GrayLog handles out of order chunks](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfChunkAggregator.java#L152) which speaks for relying on this instead.

**Comment by mp911de** [comment] 2020-01-04 13:37
Thanks for the additional details. I'm inclined to close this ticket instead of changing the default size. Given that we hadn't seen any issues since the library is in use, that's a strong signal to not change things that aren't broken.

**Comment by sfuhrm** [comment] 2020-01-04 15:15
@waldeinburg you are right, IP fragmentation can be a problem, but in the end all UDP is not working then properly in your network. IMHO you shouldn't design software for a broken environment.

GELF is not encrypted and usually not authenticated, so it's only something for local trusted networks where you can fix network problems.

**Comment by waldeinburg** [comment] 2020-01-04 20:10
Ok. I think it should then be added to the documentation that 1460 is a value which is guaranteed to work, even when UDP fragmentation is broken.

**Comment by mp911de** [comment] 2020-01-10 19:12
Documentation is updated now. Thanks all for the discussion.

**Closed by mp911de** 2020-01-10 19:12 UTC
Labels: for: team-attention, type: task
